### PR TITLE
Create initial benchmark suite

### PR DESCRIPTION
**Pull request by OnorioCatenacci**
https://github.com/christhekeele/matcha/issues/5

This is a very simple start on adding benchmarking tests to matcha.  I didn't want to add too many tests without running this by Chris Keele to insure I'm headed in the right direction.

### CODE REVIEW

**Comment by christhekeele** [comment]
I would argue that benchmarks don't really belong in the unit test suite. The convention I've seen is to have benchee in a top-level `./bench/` folder, run in a different CI task. I personally prefer the idea of adding a new dedicated suite in `./test/bench/` and adding some new mix aliases to run them.

We could also add running the benchmarks to CI, by creating a new test task [identical to this one](https://github.com/christhekeele/matcha/blob/latest/.github/workflows/test-suite.yml#L18-L55) to the suite that invokes the `mix bench` alias.

My ideal implementation of this suite would involve also somehow generating [html benchmark reports](https://github.com/bencheeorg/benchee_html) during CI, and checking it in (perhaps to a some top-level `./bench/` folder, so we can link to it in documentation and browse to it locally with `open ./bench/index.html` just like you do for ex_docs `./doc/` folder.  WDYT?

**Comment by OnorioCatenacci** [comment]
Those all sound like excellent suggestions to me Chris!  I definitely just
went with the first blog posting I found about adding benchmarking so I
have no great attachment to that particular approach.  In fact if there's a
way we can easily add the benchmarking detail to the stuff that's being
displayed for Matcha I'd consider that a great idea!

**Comment by christhekeele** [comment]
Thanks again for these @OnorioCatenacci!

I built out [a benchmark framework](https://github.com/christhekeele/matcha/pull/36) per our discussion here, and [added some machinery to auto-publish them to Github Pages](https://github.com/christhekeele/matcha/pull/36/files#diff-f9265bf8cc7addf0e33c5fd94119043c689b447369abbdcc39ae0aaefa5b5913) on updates to `latest`, and set it up [using the benchmarks you provided](https://github.com/christhekeele/matcha/pull/36/files#diff-5300f51251f69445161a77bebac27af342022f49419cd539af7948608585d9bfR13-R36) in this PR!

You can view them published (in a pretty rough format) [here](https://christhekeele.github.io/matcha/bench)! Excited to have this in place!

**Comment by OnorioCatenacci** [comment]
LOL--I was going to start working on modifying the benchmarks as you
suggested!  Coolness!

I'll keep working through the tracing livebook and if I spot anything else
that seems tricky or confusing I'll let you know.  Otherwise, after I've
done that I'll start on the tables livebook and see if I can assist you
with that doc.

**Pull request closed without merging**
