### PR TITLE
Extend select to expose all operations

### PR DESCRIPTION
**Pull request by axelson**
This is a sketch of how multiple operations can be used for `select`. If this sketch looks okay as an API (an alternative would be to create a new macro for each operation) then we can add tests.

For an example of how this could be used see: https://github.com/axelson/data_tracer/pull/2

### CODE REVIEW

**Comment by christhekeele** [comment]
I like this idea a lot! I'm honestly still trying to decide myself if I like these multiple individual functions for different "modes", vs a consolidated API with one entry point like this.

Currently I'm leaning towards both (multiple functions for doc discoverability, utility functions like these for power user access). So 🟢  green light for pursuing further!

**Comment by christhekeele** [comment]
I've been playing with this more and loved it.

I've added (provisional, undocumented, untested‚ the joys of being pre `0.2.0`!) support for this in `Matcha`'s `latest` branch, pretty much verbatim, just navigating a merge conflict in the function head.

Thanks for the contribution!

**Comment by christhekeele** [comment]
hold my 🍵, gonna try this new bot out using you as a test subject

@all-contributors please add @axelson for code, ideas

**Comment by christhekeele** [comment]
yeah that's been my experience to date

**Comment by axelson** [comment]
Nice! I'll try out the `latest` branch in my https://github.com/axelson/data_tracer project and let you know how it goes. But it should be smooth sailing.

**Comment by axelson** [comment]
@christhekeele I'm glad to be able to report that the new API is working fine!

Although I am getting a bunch of dialyzer warnings, which I can't figure out.

Code:
```
    Matcha.Table.ETS.select table, :reverse do
      {{_time, _dup_number, the_key}, value} when key == the_key -> value
    end
```

`mix dialyzer` warnings:
```
lib/data_tracer/server.ex:92:pattern_match
The pattern can never match the type.

Pattern:
:all

Type:
:reverse

________________________________________________________________________________
lib/data_tracer/server.ex:92:pattern_match
The pattern can never match the type.

Pattern:
:count

Type:
:reverse

________________________________________________________________________________
lib/data_tracer/server.ex:92:pattern_match
The pattern can never match the type.

Pattern:
:delete

Type:
:reverse

________________________________________________________________________________
lib/data_tracer/server.ex:92:pattern_match
The pattern can never match the type.

Pattern:
:replace

Type:
:reverse

________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
```

**Comment by axelson** [comment]
Hmm, maybe we just need to add `generated: true` to the quote block: https://elixirforum.com/t/dialyzer-with-a-macro-injected-case-statement/25696

    quote location: :keep, generated: true do

**Comment by christhekeele** [comment]
Ah, I think I see—we just need to take the `case` selection out of the `quote`, ex [here](https://github.com/christhekeele/matcha/blob/f100da89ded8c863a8b1f3c12bccb15bf783e405/lib/matcha/table/ets.ex#L15-L19).

The macro today generates a case statement like:

```ex
case :replace do
  :all -> ...
  :replace -> ...
end
```

which dialyzer correctly views as unneccesary control flow, that selection should within the macro.

`generated: true` would surpress this warning, but I'll just make it produce better code instead 😄

**Comment by christhekeele** [comment]
@axelson should be fixed on `latest` by [building the function call at compile time](https://github.com/christhekeele/matcha/blob/2616c745731afb99efff433f08112a183b2b3c16/lib/matcha/table/ets.ex#L28) in [this commit](https://github.com/christhekeele/matcha/commit/2616c745731afb99efff433f08112a183b2b3c16)!

**Comment by axelson** [comment]
@christhekeele thanks! That fixes the issue!

**Pull request closed without merging**
